// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proj.proto

package com.lsmichel.akka.grpc.java.rabbitmq;

public final class CardManagerRunner {
  private CardManagerRunner() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CardManager_Card_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CardManager_Card_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CardManager_CardCreateActionPerformed_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CardManager_CardCreateActionPerformed_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nproj.proto\022\013CardManager\"\362\003\n\004Card\022\016\n\006ca" +
      "rdid\030\001 \001(\001\022\025\n\rcardUserFname\030\002 \001(\t\022\025\n\rcar" +
      "dUserLname\030\003 \001(\t\022\033\n\023cardDateEtabishment\030" +
      "\004 \001(\t\022\031\n\021cardDateEpiration\030\005 \001(\t\022\036\n\026card" +
      "LocationEtabishmen\030\006 \001(\t\022\032\n\022cardImatricu" +
      "lation\030\007 \001(\t\022\022\n\ncardNumber\030\010 \001(\t\022\023\n\013card" +
      "UserSex\030\t \001(\t\022\025\n\rcardUserPhoto\030\n \001(\t\022\026\n\016" +
      "cardUserAdress\030\013 \001(\t\022\031\n\021cardUserPofessio" +
      "n\030\014 \001(\t\022\032\n\022cardUserFatherName\030\r \001(\t\022\037\n\027c" +
      "ardUserFatherBirthDate\030\016 \001(\t\022\037\n\027cardUser" +
      "MatherBirthDate\030\017 \001(\t\022\032\n\022cardUserMatherN" +
      "ame\030\020 \001(\t\022\031\n\021cardUserBirthDate\030\021 \001(\t\022\032\n\022" +
      "cardUserBrithPlace\030\022 \001(\t\022\024\n\014cardNocaisse" +
      "\030\023 \001(\t\"e\n\031CardCreateActionPerformed\022\024\n\014e" +
      "rrorMessage\030\001 \001(\t\022\020\n\010hasError\030\002 \001(\010\022\017\n\007m" +
      "essage\030\003 \001(\t\022\017\n\007numcard\030\004 \001(\t2W\n\014CardeMa" +
      "nager\022G\n\010PostCard\022\021.CardManager.Card\032&.C" +
      "ardManager.CardCreateActionPerformed\"\000B;" +
      "\n$com.lsmichel.akka.grpc.java.rabbitmqB\021" +
      "CardManagerRunnerP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CardManager_Card_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CardManager_Card_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CardManager_Card_descriptor,
        new java.lang.String[] { "Cardid", "CardUserFname", "CardUserLname", "CardDateEtabishment", "CardDateEpiration", "CardLocationEtabishmen", "CardImatriculation", "CardNumber", "CardUserSex", "CardUserPhoto", "CardUserAdress", "CardUserPofession", "CardUserFatherName", "CardUserFatherBirthDate", "CardUserMatherBirthDate", "CardUserMatherName", "CardUserBirthDate", "CardUserBrithPlace", "CardNocaisse", });
    internal_static_CardManager_CardCreateActionPerformed_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CardManager_CardCreateActionPerformed_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CardManager_CardCreateActionPerformed_descriptor,
        new java.lang.String[] { "ErrorMessage", "HasError", "Message", "Numcard", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
