// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proj.proto

package com.lsmichel.akka.grpc.java.rabbitmq;

public interface CardOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CardManager.Card)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double cardid = 1;</code>
   */
  double getCardid();

  /**
   * <code>string cardUserFname = 2;</code>
   */
  java.lang.String getCardUserFname();
  /**
   * <code>string cardUserFname = 2;</code>
   */
  com.google.protobuf.ByteString
      getCardUserFnameBytes();

  /**
   * <code>string cardUserLname = 3;</code>
   */
  java.lang.String getCardUserLname();
  /**
   * <code>string cardUserLname = 3;</code>
   */
  com.google.protobuf.ByteString
      getCardUserLnameBytes();

  /**
   * <code>string cardDateEtabishment = 4;</code>
   */
  java.lang.String getCardDateEtabishment();
  /**
   * <code>string cardDateEtabishment = 4;</code>
   */
  com.google.protobuf.ByteString
      getCardDateEtabishmentBytes();

  /**
   * <code>string cardDateEpiration = 5;</code>
   */
  java.lang.String getCardDateEpiration();
  /**
   * <code>string cardDateEpiration = 5;</code>
   */
  com.google.protobuf.ByteString
      getCardDateEpirationBytes();

  /**
   * <code>string cardLocationEtabishmen = 6;</code>
   */
  java.lang.String getCardLocationEtabishmen();
  /**
   * <code>string cardLocationEtabishmen = 6;</code>
   */
  com.google.protobuf.ByteString
      getCardLocationEtabishmenBytes();

  /**
   * <code>string cardImatriculation = 7;</code>
   */
  java.lang.String getCardImatriculation();
  /**
   * <code>string cardImatriculation = 7;</code>
   */
  com.google.protobuf.ByteString
      getCardImatriculationBytes();

  /**
   * <code>string cardNumber = 8;</code>
   */
  java.lang.String getCardNumber();
  /**
   * <code>string cardNumber = 8;</code>
   */
  com.google.protobuf.ByteString
      getCardNumberBytes();

  /**
   * <code>string cardUserSex = 9;</code>
   */
  java.lang.String getCardUserSex();
  /**
   * <code>string cardUserSex = 9;</code>
   */
  com.google.protobuf.ByteString
      getCardUserSexBytes();

  /**
   * <code>string cardUserPhoto = 10;</code>
   */
  java.lang.String getCardUserPhoto();
  /**
   * <code>string cardUserPhoto = 10;</code>
   */
  com.google.protobuf.ByteString
      getCardUserPhotoBytes();

  /**
   * <code>string cardUserAdress = 11;</code>
   */
  java.lang.String getCardUserAdress();
  /**
   * <code>string cardUserAdress = 11;</code>
   */
  com.google.protobuf.ByteString
      getCardUserAdressBytes();

  /**
   * <code>string cardUserPofession = 12;</code>
   */
  java.lang.String getCardUserPofession();
  /**
   * <code>string cardUserPofession = 12;</code>
   */
  com.google.protobuf.ByteString
      getCardUserPofessionBytes();

  /**
   * <code>string cardUserFatherName = 13;</code>
   */
  java.lang.String getCardUserFatherName();
  /**
   * <code>string cardUserFatherName = 13;</code>
   */
  com.google.protobuf.ByteString
      getCardUserFatherNameBytes();

  /**
   * <code>string cardUserFatherBirthDate = 14;</code>
   */
  java.lang.String getCardUserFatherBirthDate();
  /**
   * <code>string cardUserFatherBirthDate = 14;</code>
   */
  com.google.protobuf.ByteString
      getCardUserFatherBirthDateBytes();

  /**
   * <code>string cardUserMatherBirthDate = 15;</code>
   */
  java.lang.String getCardUserMatherBirthDate();
  /**
   * <code>string cardUserMatherBirthDate = 15;</code>
   */
  com.google.protobuf.ByteString
      getCardUserMatherBirthDateBytes();

  /**
   * <code>string cardUserMatherName = 16;</code>
   */
  java.lang.String getCardUserMatherName();
  /**
   * <code>string cardUserMatherName = 16;</code>
   */
  com.google.protobuf.ByteString
      getCardUserMatherNameBytes();

  /**
   * <code>string cardUserBirthDate = 17;</code>
   */
  java.lang.String getCardUserBirthDate();
  /**
   * <code>string cardUserBirthDate = 17;</code>
   */
  com.google.protobuf.ByteString
      getCardUserBirthDateBytes();

  /**
   * <code>string cardUserBrithPlace = 18;</code>
   */
  java.lang.String getCardUserBrithPlace();
  /**
   * <code>string cardUserBrithPlace = 18;</code>
   */
  com.google.protobuf.ByteString
      getCardUserBrithPlaceBytes();

  /**
   * <code>string cardNocaisse = 19;</code>
   */
  java.lang.String getCardNocaisse();
  /**
   * <code>string cardNocaisse = 19;</code>
   */
  com.google.protobuf.ByteString
      getCardNocaisseBytes();
}
