// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proj.proto

package com.lsmichel.akka.grpc.java.rabbitmq;

/**
 * Protobuf type {@code CardManager.Card}
 */
public  final class Card extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:CardManager.Card)
    CardOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Card.newBuilder() to construct.
  private Card(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Card() {
    cardid_ = 0D;
    cardUserFname_ = "";
    cardUserLname_ = "";
    cardDateEtabishment_ = "";
    cardDateEpiration_ = "";
    cardLocationEtabishmen_ = "";
    cardImatriculation_ = "";
    cardNumber_ = "";
    cardUserSex_ = "";
    cardUserPhoto_ = "";
    cardUserAdress_ = "";
    cardUserPofession_ = "";
    cardUserFatherName_ = "";
    cardUserFatherBirthDate_ = "";
    cardUserMatherBirthDate_ = "";
    cardUserMatherName_ = "";
    cardUserBirthDate_ = "";
    cardUserBrithPlace_ = "";
    cardNocaisse_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Card(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 9: {

            cardid_ = input.readDouble();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            cardUserFname_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            cardUserLname_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            cardDateEtabishment_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            cardDateEpiration_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            cardLocationEtabishmen_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            cardImatriculation_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            cardNumber_ = s;
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            cardUserSex_ = s;
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            cardUserPhoto_ = s;
            break;
          }
          case 90: {
            java.lang.String s = input.readStringRequireUtf8();

            cardUserAdress_ = s;
            break;
          }
          case 98: {
            java.lang.String s = input.readStringRequireUtf8();

            cardUserPofession_ = s;
            break;
          }
          case 106: {
            java.lang.String s = input.readStringRequireUtf8();

            cardUserFatherName_ = s;
            break;
          }
          case 114: {
            java.lang.String s = input.readStringRequireUtf8();

            cardUserFatherBirthDate_ = s;
            break;
          }
          case 122: {
            java.lang.String s = input.readStringRequireUtf8();

            cardUserMatherBirthDate_ = s;
            break;
          }
          case 130: {
            java.lang.String s = input.readStringRequireUtf8();

            cardUserMatherName_ = s;
            break;
          }
          case 138: {
            java.lang.String s = input.readStringRequireUtf8();

            cardUserBirthDate_ = s;
            break;
          }
          case 146: {
            java.lang.String s = input.readStringRequireUtf8();

            cardUserBrithPlace_ = s;
            break;
          }
          case 154: {
            java.lang.String s = input.readStringRequireUtf8();

            cardNocaisse_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.lsmichel.akka.grpc.java.rabbitmq.CardManagerRunner.internal_static_CardManager_Card_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.lsmichel.akka.grpc.java.rabbitmq.CardManagerRunner.internal_static_CardManager_Card_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.lsmichel.akka.grpc.java.rabbitmq.Card.class, com.lsmichel.akka.grpc.java.rabbitmq.Card.Builder.class);
  }

  public static final int CARDID_FIELD_NUMBER = 1;
  private double cardid_;
  /**
   * <code>double cardid = 1;</code>
   */
  public double getCardid() {
    return cardid_;
  }

  public static final int CARDUSERFNAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object cardUserFname_;
  /**
   * <code>string cardUserFname = 2;</code>
   */
  public java.lang.String getCardUserFname() {
    java.lang.Object ref = cardUserFname_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cardUserFname_ = s;
      return s;
    }
  }
  /**
   * <code>string cardUserFname = 2;</code>
   */
  public com.google.protobuf.ByteString
      getCardUserFnameBytes() {
    java.lang.Object ref = cardUserFname_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cardUserFname_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CARDUSERLNAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object cardUserLname_;
  /**
   * <code>string cardUserLname = 3;</code>
   */
  public java.lang.String getCardUserLname() {
    java.lang.Object ref = cardUserLname_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cardUserLname_ = s;
      return s;
    }
  }
  /**
   * <code>string cardUserLname = 3;</code>
   */
  public com.google.protobuf.ByteString
      getCardUserLnameBytes() {
    java.lang.Object ref = cardUserLname_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cardUserLname_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CARDDATEETABISHMENT_FIELD_NUMBER = 4;
  private volatile java.lang.Object cardDateEtabishment_;
  /**
   * <code>string cardDateEtabishment = 4;</code>
   */
  public java.lang.String getCardDateEtabishment() {
    java.lang.Object ref = cardDateEtabishment_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cardDateEtabishment_ = s;
      return s;
    }
  }
  /**
   * <code>string cardDateEtabishment = 4;</code>
   */
  public com.google.protobuf.ByteString
      getCardDateEtabishmentBytes() {
    java.lang.Object ref = cardDateEtabishment_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cardDateEtabishment_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CARDDATEEPIRATION_FIELD_NUMBER = 5;
  private volatile java.lang.Object cardDateEpiration_;
  /**
   * <code>string cardDateEpiration = 5;</code>
   */
  public java.lang.String getCardDateEpiration() {
    java.lang.Object ref = cardDateEpiration_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cardDateEpiration_ = s;
      return s;
    }
  }
  /**
   * <code>string cardDateEpiration = 5;</code>
   */
  public com.google.protobuf.ByteString
      getCardDateEpirationBytes() {
    java.lang.Object ref = cardDateEpiration_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cardDateEpiration_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CARDLOCATIONETABISHMEN_FIELD_NUMBER = 6;
  private volatile java.lang.Object cardLocationEtabishmen_;
  /**
   * <code>string cardLocationEtabishmen = 6;</code>
   */
  public java.lang.String getCardLocationEtabishmen() {
    java.lang.Object ref = cardLocationEtabishmen_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cardLocationEtabishmen_ = s;
      return s;
    }
  }
  /**
   * <code>string cardLocationEtabishmen = 6;</code>
   */
  public com.google.protobuf.ByteString
      getCardLocationEtabishmenBytes() {
    java.lang.Object ref = cardLocationEtabishmen_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cardLocationEtabishmen_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CARDIMATRICULATION_FIELD_NUMBER = 7;
  private volatile java.lang.Object cardImatriculation_;
  /**
   * <code>string cardImatriculation = 7;</code>
   */
  public java.lang.String getCardImatriculation() {
    java.lang.Object ref = cardImatriculation_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cardImatriculation_ = s;
      return s;
    }
  }
  /**
   * <code>string cardImatriculation = 7;</code>
   */
  public com.google.protobuf.ByteString
      getCardImatriculationBytes() {
    java.lang.Object ref = cardImatriculation_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cardImatriculation_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CARDNUMBER_FIELD_NUMBER = 8;
  private volatile java.lang.Object cardNumber_;
  /**
   * <code>string cardNumber = 8;</code>
   */
  public java.lang.String getCardNumber() {
    java.lang.Object ref = cardNumber_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cardNumber_ = s;
      return s;
    }
  }
  /**
   * <code>string cardNumber = 8;</code>
   */
  public com.google.protobuf.ByteString
      getCardNumberBytes() {
    java.lang.Object ref = cardNumber_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cardNumber_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CARDUSERSEX_FIELD_NUMBER = 9;
  private volatile java.lang.Object cardUserSex_;
  /**
   * <code>string cardUserSex = 9;</code>
   */
  public java.lang.String getCardUserSex() {
    java.lang.Object ref = cardUserSex_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cardUserSex_ = s;
      return s;
    }
  }
  /**
   * <code>string cardUserSex = 9;</code>
   */
  public com.google.protobuf.ByteString
      getCardUserSexBytes() {
    java.lang.Object ref = cardUserSex_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cardUserSex_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CARDUSERPHOTO_FIELD_NUMBER = 10;
  private volatile java.lang.Object cardUserPhoto_;
  /**
   * <code>string cardUserPhoto = 10;</code>
   */
  public java.lang.String getCardUserPhoto() {
    java.lang.Object ref = cardUserPhoto_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cardUserPhoto_ = s;
      return s;
    }
  }
  /**
   * <code>string cardUserPhoto = 10;</code>
   */
  public com.google.protobuf.ByteString
      getCardUserPhotoBytes() {
    java.lang.Object ref = cardUserPhoto_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cardUserPhoto_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CARDUSERADRESS_FIELD_NUMBER = 11;
  private volatile java.lang.Object cardUserAdress_;
  /**
   * <code>string cardUserAdress = 11;</code>
   */
  public java.lang.String getCardUserAdress() {
    java.lang.Object ref = cardUserAdress_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cardUserAdress_ = s;
      return s;
    }
  }
  /**
   * <code>string cardUserAdress = 11;</code>
   */
  public com.google.protobuf.ByteString
      getCardUserAdressBytes() {
    java.lang.Object ref = cardUserAdress_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cardUserAdress_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CARDUSERPOFESSION_FIELD_NUMBER = 12;
  private volatile java.lang.Object cardUserPofession_;
  /**
   * <code>string cardUserPofession = 12;</code>
   */
  public java.lang.String getCardUserPofession() {
    java.lang.Object ref = cardUserPofession_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cardUserPofession_ = s;
      return s;
    }
  }
  /**
   * <code>string cardUserPofession = 12;</code>
   */
  public com.google.protobuf.ByteString
      getCardUserPofessionBytes() {
    java.lang.Object ref = cardUserPofession_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cardUserPofession_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CARDUSERFATHERNAME_FIELD_NUMBER = 13;
  private volatile java.lang.Object cardUserFatherName_;
  /**
   * <code>string cardUserFatherName = 13;</code>
   */
  public java.lang.String getCardUserFatherName() {
    java.lang.Object ref = cardUserFatherName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cardUserFatherName_ = s;
      return s;
    }
  }
  /**
   * <code>string cardUserFatherName = 13;</code>
   */
  public com.google.protobuf.ByteString
      getCardUserFatherNameBytes() {
    java.lang.Object ref = cardUserFatherName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cardUserFatherName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CARDUSERFATHERBIRTHDATE_FIELD_NUMBER = 14;
  private volatile java.lang.Object cardUserFatherBirthDate_;
  /**
   * <code>string cardUserFatherBirthDate = 14;</code>
   */
  public java.lang.String getCardUserFatherBirthDate() {
    java.lang.Object ref = cardUserFatherBirthDate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cardUserFatherBirthDate_ = s;
      return s;
    }
  }
  /**
   * <code>string cardUserFatherBirthDate = 14;</code>
   */
  public com.google.protobuf.ByteString
      getCardUserFatherBirthDateBytes() {
    java.lang.Object ref = cardUserFatherBirthDate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cardUserFatherBirthDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CARDUSERMATHERBIRTHDATE_FIELD_NUMBER = 15;
  private volatile java.lang.Object cardUserMatherBirthDate_;
  /**
   * <code>string cardUserMatherBirthDate = 15;</code>
   */
  public java.lang.String getCardUserMatherBirthDate() {
    java.lang.Object ref = cardUserMatherBirthDate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cardUserMatherBirthDate_ = s;
      return s;
    }
  }
  /**
   * <code>string cardUserMatherBirthDate = 15;</code>
   */
  public com.google.protobuf.ByteString
      getCardUserMatherBirthDateBytes() {
    java.lang.Object ref = cardUserMatherBirthDate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cardUserMatherBirthDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CARDUSERMATHERNAME_FIELD_NUMBER = 16;
  private volatile java.lang.Object cardUserMatherName_;
  /**
   * <code>string cardUserMatherName = 16;</code>
   */
  public java.lang.String getCardUserMatherName() {
    java.lang.Object ref = cardUserMatherName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cardUserMatherName_ = s;
      return s;
    }
  }
  /**
   * <code>string cardUserMatherName = 16;</code>
   */
  public com.google.protobuf.ByteString
      getCardUserMatherNameBytes() {
    java.lang.Object ref = cardUserMatherName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cardUserMatherName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CARDUSERBIRTHDATE_FIELD_NUMBER = 17;
  private volatile java.lang.Object cardUserBirthDate_;
  /**
   * <code>string cardUserBirthDate = 17;</code>
   */
  public java.lang.String getCardUserBirthDate() {
    java.lang.Object ref = cardUserBirthDate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cardUserBirthDate_ = s;
      return s;
    }
  }
  /**
   * <code>string cardUserBirthDate = 17;</code>
   */
  public com.google.protobuf.ByteString
      getCardUserBirthDateBytes() {
    java.lang.Object ref = cardUserBirthDate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cardUserBirthDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CARDUSERBRITHPLACE_FIELD_NUMBER = 18;
  private volatile java.lang.Object cardUserBrithPlace_;
  /**
   * <code>string cardUserBrithPlace = 18;</code>
   */
  public java.lang.String getCardUserBrithPlace() {
    java.lang.Object ref = cardUserBrithPlace_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cardUserBrithPlace_ = s;
      return s;
    }
  }
  /**
   * <code>string cardUserBrithPlace = 18;</code>
   */
  public com.google.protobuf.ByteString
      getCardUserBrithPlaceBytes() {
    java.lang.Object ref = cardUserBrithPlace_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cardUserBrithPlace_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CARDNOCAISSE_FIELD_NUMBER = 19;
  private volatile java.lang.Object cardNocaisse_;
  /**
   * <code>string cardNocaisse = 19;</code>
   */
  public java.lang.String getCardNocaisse() {
    java.lang.Object ref = cardNocaisse_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cardNocaisse_ = s;
      return s;
    }
  }
  /**
   * <code>string cardNocaisse = 19;</code>
   */
  public com.google.protobuf.ByteString
      getCardNocaisseBytes() {
    java.lang.Object ref = cardNocaisse_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cardNocaisse_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (cardid_ != 0D) {
      output.writeDouble(1, cardid_);
    }
    if (!getCardUserFnameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, cardUserFname_);
    }
    if (!getCardUserLnameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, cardUserLname_);
    }
    if (!getCardDateEtabishmentBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, cardDateEtabishment_);
    }
    if (!getCardDateEpirationBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, cardDateEpiration_);
    }
    if (!getCardLocationEtabishmenBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, cardLocationEtabishmen_);
    }
    if (!getCardImatriculationBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, cardImatriculation_);
    }
    if (!getCardNumberBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, cardNumber_);
    }
    if (!getCardUserSexBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, cardUserSex_);
    }
    if (!getCardUserPhotoBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, cardUserPhoto_);
    }
    if (!getCardUserAdressBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, cardUserAdress_);
    }
    if (!getCardUserPofessionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, cardUserPofession_);
    }
    if (!getCardUserFatherNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 13, cardUserFatherName_);
    }
    if (!getCardUserFatherBirthDateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 14, cardUserFatherBirthDate_);
    }
    if (!getCardUserMatherBirthDateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 15, cardUserMatherBirthDate_);
    }
    if (!getCardUserMatherNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 16, cardUserMatherName_);
    }
    if (!getCardUserBirthDateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 17, cardUserBirthDate_);
    }
    if (!getCardUserBrithPlaceBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 18, cardUserBrithPlace_);
    }
    if (!getCardNocaisseBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 19, cardNocaisse_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (cardid_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, cardid_);
    }
    if (!getCardUserFnameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, cardUserFname_);
    }
    if (!getCardUserLnameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, cardUserLname_);
    }
    if (!getCardDateEtabishmentBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, cardDateEtabishment_);
    }
    if (!getCardDateEpirationBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, cardDateEpiration_);
    }
    if (!getCardLocationEtabishmenBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, cardLocationEtabishmen_);
    }
    if (!getCardImatriculationBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, cardImatriculation_);
    }
    if (!getCardNumberBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, cardNumber_);
    }
    if (!getCardUserSexBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, cardUserSex_);
    }
    if (!getCardUserPhotoBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, cardUserPhoto_);
    }
    if (!getCardUserAdressBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, cardUserAdress_);
    }
    if (!getCardUserPofessionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, cardUserPofession_);
    }
    if (!getCardUserFatherNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, cardUserFatherName_);
    }
    if (!getCardUserFatherBirthDateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, cardUserFatherBirthDate_);
    }
    if (!getCardUserMatherBirthDateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, cardUserMatherBirthDate_);
    }
    if (!getCardUserMatherNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(16, cardUserMatherName_);
    }
    if (!getCardUserBirthDateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(17, cardUserBirthDate_);
    }
    if (!getCardUserBrithPlaceBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(18, cardUserBrithPlace_);
    }
    if (!getCardNocaisseBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(19, cardNocaisse_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.lsmichel.akka.grpc.java.rabbitmq.Card)) {
      return super.equals(obj);
    }
    com.lsmichel.akka.grpc.java.rabbitmq.Card other = (com.lsmichel.akka.grpc.java.rabbitmq.Card) obj;

    boolean result = true;
    result = result && (
        java.lang.Double.doubleToLongBits(getCardid())
        == java.lang.Double.doubleToLongBits(
            other.getCardid()));
    result = result && getCardUserFname()
        .equals(other.getCardUserFname());
    result = result && getCardUserLname()
        .equals(other.getCardUserLname());
    result = result && getCardDateEtabishment()
        .equals(other.getCardDateEtabishment());
    result = result && getCardDateEpiration()
        .equals(other.getCardDateEpiration());
    result = result && getCardLocationEtabishmen()
        .equals(other.getCardLocationEtabishmen());
    result = result && getCardImatriculation()
        .equals(other.getCardImatriculation());
    result = result && getCardNumber()
        .equals(other.getCardNumber());
    result = result && getCardUserSex()
        .equals(other.getCardUserSex());
    result = result && getCardUserPhoto()
        .equals(other.getCardUserPhoto());
    result = result && getCardUserAdress()
        .equals(other.getCardUserAdress());
    result = result && getCardUserPofession()
        .equals(other.getCardUserPofession());
    result = result && getCardUserFatherName()
        .equals(other.getCardUserFatherName());
    result = result && getCardUserFatherBirthDate()
        .equals(other.getCardUserFatherBirthDate());
    result = result && getCardUserMatherBirthDate()
        .equals(other.getCardUserMatherBirthDate());
    result = result && getCardUserMatherName()
        .equals(other.getCardUserMatherName());
    result = result && getCardUserBirthDate()
        .equals(other.getCardUserBirthDate());
    result = result && getCardUserBrithPlace()
        .equals(other.getCardUserBrithPlace());
    result = result && getCardNocaisse()
        .equals(other.getCardNocaisse());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CARDID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getCardid()));
    hash = (37 * hash) + CARDUSERFNAME_FIELD_NUMBER;
    hash = (53 * hash) + getCardUserFname().hashCode();
    hash = (37 * hash) + CARDUSERLNAME_FIELD_NUMBER;
    hash = (53 * hash) + getCardUserLname().hashCode();
    hash = (37 * hash) + CARDDATEETABISHMENT_FIELD_NUMBER;
    hash = (53 * hash) + getCardDateEtabishment().hashCode();
    hash = (37 * hash) + CARDDATEEPIRATION_FIELD_NUMBER;
    hash = (53 * hash) + getCardDateEpiration().hashCode();
    hash = (37 * hash) + CARDLOCATIONETABISHMEN_FIELD_NUMBER;
    hash = (53 * hash) + getCardLocationEtabishmen().hashCode();
    hash = (37 * hash) + CARDIMATRICULATION_FIELD_NUMBER;
    hash = (53 * hash) + getCardImatriculation().hashCode();
    hash = (37 * hash) + CARDNUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getCardNumber().hashCode();
    hash = (37 * hash) + CARDUSERSEX_FIELD_NUMBER;
    hash = (53 * hash) + getCardUserSex().hashCode();
    hash = (37 * hash) + CARDUSERPHOTO_FIELD_NUMBER;
    hash = (53 * hash) + getCardUserPhoto().hashCode();
    hash = (37 * hash) + CARDUSERADRESS_FIELD_NUMBER;
    hash = (53 * hash) + getCardUserAdress().hashCode();
    hash = (37 * hash) + CARDUSERPOFESSION_FIELD_NUMBER;
    hash = (53 * hash) + getCardUserPofession().hashCode();
    hash = (37 * hash) + CARDUSERFATHERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getCardUserFatherName().hashCode();
    hash = (37 * hash) + CARDUSERFATHERBIRTHDATE_FIELD_NUMBER;
    hash = (53 * hash) + getCardUserFatherBirthDate().hashCode();
    hash = (37 * hash) + CARDUSERMATHERBIRTHDATE_FIELD_NUMBER;
    hash = (53 * hash) + getCardUserMatherBirthDate().hashCode();
    hash = (37 * hash) + CARDUSERMATHERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getCardUserMatherName().hashCode();
    hash = (37 * hash) + CARDUSERBIRTHDATE_FIELD_NUMBER;
    hash = (53 * hash) + getCardUserBirthDate().hashCode();
    hash = (37 * hash) + CARDUSERBRITHPLACE_FIELD_NUMBER;
    hash = (53 * hash) + getCardUserBrithPlace().hashCode();
    hash = (37 * hash) + CARDNOCAISSE_FIELD_NUMBER;
    hash = (53 * hash) + getCardNocaisse().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.lsmichel.akka.grpc.java.rabbitmq.Card parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lsmichel.akka.grpc.java.rabbitmq.Card parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lsmichel.akka.grpc.java.rabbitmq.Card parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lsmichel.akka.grpc.java.rabbitmq.Card parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lsmichel.akka.grpc.java.rabbitmq.Card parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lsmichel.akka.grpc.java.rabbitmq.Card parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lsmichel.akka.grpc.java.rabbitmq.Card parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.lsmichel.akka.grpc.java.rabbitmq.Card parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.lsmichel.akka.grpc.java.rabbitmq.Card parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.lsmichel.akka.grpc.java.rabbitmq.Card parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.lsmichel.akka.grpc.java.rabbitmq.Card parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.lsmichel.akka.grpc.java.rabbitmq.Card parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.lsmichel.akka.grpc.java.rabbitmq.Card prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code CardManager.Card}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:CardManager.Card)
      com.lsmichel.akka.grpc.java.rabbitmq.CardOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lsmichel.akka.grpc.java.rabbitmq.CardManagerRunner.internal_static_CardManager_Card_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lsmichel.akka.grpc.java.rabbitmq.CardManagerRunner.internal_static_CardManager_Card_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lsmichel.akka.grpc.java.rabbitmq.Card.class, com.lsmichel.akka.grpc.java.rabbitmq.Card.Builder.class);
    }

    // Construct using com.lsmichel.akka.grpc.java.rabbitmq.Card.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      cardid_ = 0D;

      cardUserFname_ = "";

      cardUserLname_ = "";

      cardDateEtabishment_ = "";

      cardDateEpiration_ = "";

      cardLocationEtabishmen_ = "";

      cardImatriculation_ = "";

      cardNumber_ = "";

      cardUserSex_ = "";

      cardUserPhoto_ = "";

      cardUserAdress_ = "";

      cardUserPofession_ = "";

      cardUserFatherName_ = "";

      cardUserFatherBirthDate_ = "";

      cardUserMatherBirthDate_ = "";

      cardUserMatherName_ = "";

      cardUserBirthDate_ = "";

      cardUserBrithPlace_ = "";

      cardNocaisse_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.lsmichel.akka.grpc.java.rabbitmq.CardManagerRunner.internal_static_CardManager_Card_descriptor;
    }

    public com.lsmichel.akka.grpc.java.rabbitmq.Card getDefaultInstanceForType() {
      return com.lsmichel.akka.grpc.java.rabbitmq.Card.getDefaultInstance();
    }

    public com.lsmichel.akka.grpc.java.rabbitmq.Card build() {
      com.lsmichel.akka.grpc.java.rabbitmq.Card result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.lsmichel.akka.grpc.java.rabbitmq.Card buildPartial() {
      com.lsmichel.akka.grpc.java.rabbitmq.Card result = new com.lsmichel.akka.grpc.java.rabbitmq.Card(this);
      result.cardid_ = cardid_;
      result.cardUserFname_ = cardUserFname_;
      result.cardUserLname_ = cardUserLname_;
      result.cardDateEtabishment_ = cardDateEtabishment_;
      result.cardDateEpiration_ = cardDateEpiration_;
      result.cardLocationEtabishmen_ = cardLocationEtabishmen_;
      result.cardImatriculation_ = cardImatriculation_;
      result.cardNumber_ = cardNumber_;
      result.cardUserSex_ = cardUserSex_;
      result.cardUserPhoto_ = cardUserPhoto_;
      result.cardUserAdress_ = cardUserAdress_;
      result.cardUserPofession_ = cardUserPofession_;
      result.cardUserFatherName_ = cardUserFatherName_;
      result.cardUserFatherBirthDate_ = cardUserFatherBirthDate_;
      result.cardUserMatherBirthDate_ = cardUserMatherBirthDate_;
      result.cardUserMatherName_ = cardUserMatherName_;
      result.cardUserBirthDate_ = cardUserBirthDate_;
      result.cardUserBrithPlace_ = cardUserBrithPlace_;
      result.cardNocaisse_ = cardNocaisse_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.lsmichel.akka.grpc.java.rabbitmq.Card) {
        return mergeFrom((com.lsmichel.akka.grpc.java.rabbitmq.Card)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.lsmichel.akka.grpc.java.rabbitmq.Card other) {
      if (other == com.lsmichel.akka.grpc.java.rabbitmq.Card.getDefaultInstance()) return this;
      if (other.getCardid() != 0D) {
        setCardid(other.getCardid());
      }
      if (!other.getCardUserFname().isEmpty()) {
        cardUserFname_ = other.cardUserFname_;
        onChanged();
      }
      if (!other.getCardUserLname().isEmpty()) {
        cardUserLname_ = other.cardUserLname_;
        onChanged();
      }
      if (!other.getCardDateEtabishment().isEmpty()) {
        cardDateEtabishment_ = other.cardDateEtabishment_;
        onChanged();
      }
      if (!other.getCardDateEpiration().isEmpty()) {
        cardDateEpiration_ = other.cardDateEpiration_;
        onChanged();
      }
      if (!other.getCardLocationEtabishmen().isEmpty()) {
        cardLocationEtabishmen_ = other.cardLocationEtabishmen_;
        onChanged();
      }
      if (!other.getCardImatriculation().isEmpty()) {
        cardImatriculation_ = other.cardImatriculation_;
        onChanged();
      }
      if (!other.getCardNumber().isEmpty()) {
        cardNumber_ = other.cardNumber_;
        onChanged();
      }
      if (!other.getCardUserSex().isEmpty()) {
        cardUserSex_ = other.cardUserSex_;
        onChanged();
      }
      if (!other.getCardUserPhoto().isEmpty()) {
        cardUserPhoto_ = other.cardUserPhoto_;
        onChanged();
      }
      if (!other.getCardUserAdress().isEmpty()) {
        cardUserAdress_ = other.cardUserAdress_;
        onChanged();
      }
      if (!other.getCardUserPofession().isEmpty()) {
        cardUserPofession_ = other.cardUserPofession_;
        onChanged();
      }
      if (!other.getCardUserFatherName().isEmpty()) {
        cardUserFatherName_ = other.cardUserFatherName_;
        onChanged();
      }
      if (!other.getCardUserFatherBirthDate().isEmpty()) {
        cardUserFatherBirthDate_ = other.cardUserFatherBirthDate_;
        onChanged();
      }
      if (!other.getCardUserMatherBirthDate().isEmpty()) {
        cardUserMatherBirthDate_ = other.cardUserMatherBirthDate_;
        onChanged();
      }
      if (!other.getCardUserMatherName().isEmpty()) {
        cardUserMatherName_ = other.cardUserMatherName_;
        onChanged();
      }
      if (!other.getCardUserBirthDate().isEmpty()) {
        cardUserBirthDate_ = other.cardUserBirthDate_;
        onChanged();
      }
      if (!other.getCardUserBrithPlace().isEmpty()) {
        cardUserBrithPlace_ = other.cardUserBrithPlace_;
        onChanged();
      }
      if (!other.getCardNocaisse().isEmpty()) {
        cardNocaisse_ = other.cardNocaisse_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.lsmichel.akka.grpc.java.rabbitmq.Card parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.lsmichel.akka.grpc.java.rabbitmq.Card) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private double cardid_ ;
    /**
     * <code>double cardid = 1;</code>
     */
    public double getCardid() {
      return cardid_;
    }
    /**
     * <code>double cardid = 1;</code>
     */
    public Builder setCardid(double value) {
      
      cardid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double cardid = 1;</code>
     */
    public Builder clearCardid() {
      
      cardid_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object cardUserFname_ = "";
    /**
     * <code>string cardUserFname = 2;</code>
     */
    public java.lang.String getCardUserFname() {
      java.lang.Object ref = cardUserFname_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cardUserFname_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string cardUserFname = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCardUserFnameBytes() {
      java.lang.Object ref = cardUserFname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cardUserFname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string cardUserFname = 2;</code>
     */
    public Builder setCardUserFname(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cardUserFname_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string cardUserFname = 2;</code>
     */
    public Builder clearCardUserFname() {
      
      cardUserFname_ = getDefaultInstance().getCardUserFname();
      onChanged();
      return this;
    }
    /**
     * <code>string cardUserFname = 2;</code>
     */
    public Builder setCardUserFnameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cardUserFname_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object cardUserLname_ = "";
    /**
     * <code>string cardUserLname = 3;</code>
     */
    public java.lang.String getCardUserLname() {
      java.lang.Object ref = cardUserLname_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cardUserLname_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string cardUserLname = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCardUserLnameBytes() {
      java.lang.Object ref = cardUserLname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cardUserLname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string cardUserLname = 3;</code>
     */
    public Builder setCardUserLname(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cardUserLname_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string cardUserLname = 3;</code>
     */
    public Builder clearCardUserLname() {
      
      cardUserLname_ = getDefaultInstance().getCardUserLname();
      onChanged();
      return this;
    }
    /**
     * <code>string cardUserLname = 3;</code>
     */
    public Builder setCardUserLnameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cardUserLname_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object cardDateEtabishment_ = "";
    /**
     * <code>string cardDateEtabishment = 4;</code>
     */
    public java.lang.String getCardDateEtabishment() {
      java.lang.Object ref = cardDateEtabishment_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cardDateEtabishment_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string cardDateEtabishment = 4;</code>
     */
    public com.google.protobuf.ByteString
        getCardDateEtabishmentBytes() {
      java.lang.Object ref = cardDateEtabishment_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cardDateEtabishment_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string cardDateEtabishment = 4;</code>
     */
    public Builder setCardDateEtabishment(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cardDateEtabishment_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string cardDateEtabishment = 4;</code>
     */
    public Builder clearCardDateEtabishment() {
      
      cardDateEtabishment_ = getDefaultInstance().getCardDateEtabishment();
      onChanged();
      return this;
    }
    /**
     * <code>string cardDateEtabishment = 4;</code>
     */
    public Builder setCardDateEtabishmentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cardDateEtabishment_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object cardDateEpiration_ = "";
    /**
     * <code>string cardDateEpiration = 5;</code>
     */
    public java.lang.String getCardDateEpiration() {
      java.lang.Object ref = cardDateEpiration_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cardDateEpiration_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string cardDateEpiration = 5;</code>
     */
    public com.google.protobuf.ByteString
        getCardDateEpirationBytes() {
      java.lang.Object ref = cardDateEpiration_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cardDateEpiration_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string cardDateEpiration = 5;</code>
     */
    public Builder setCardDateEpiration(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cardDateEpiration_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string cardDateEpiration = 5;</code>
     */
    public Builder clearCardDateEpiration() {
      
      cardDateEpiration_ = getDefaultInstance().getCardDateEpiration();
      onChanged();
      return this;
    }
    /**
     * <code>string cardDateEpiration = 5;</code>
     */
    public Builder setCardDateEpirationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cardDateEpiration_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object cardLocationEtabishmen_ = "";
    /**
     * <code>string cardLocationEtabishmen = 6;</code>
     */
    public java.lang.String getCardLocationEtabishmen() {
      java.lang.Object ref = cardLocationEtabishmen_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cardLocationEtabishmen_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string cardLocationEtabishmen = 6;</code>
     */
    public com.google.protobuf.ByteString
        getCardLocationEtabishmenBytes() {
      java.lang.Object ref = cardLocationEtabishmen_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cardLocationEtabishmen_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string cardLocationEtabishmen = 6;</code>
     */
    public Builder setCardLocationEtabishmen(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cardLocationEtabishmen_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string cardLocationEtabishmen = 6;</code>
     */
    public Builder clearCardLocationEtabishmen() {
      
      cardLocationEtabishmen_ = getDefaultInstance().getCardLocationEtabishmen();
      onChanged();
      return this;
    }
    /**
     * <code>string cardLocationEtabishmen = 6;</code>
     */
    public Builder setCardLocationEtabishmenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cardLocationEtabishmen_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object cardImatriculation_ = "";
    /**
     * <code>string cardImatriculation = 7;</code>
     */
    public java.lang.String getCardImatriculation() {
      java.lang.Object ref = cardImatriculation_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cardImatriculation_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string cardImatriculation = 7;</code>
     */
    public com.google.protobuf.ByteString
        getCardImatriculationBytes() {
      java.lang.Object ref = cardImatriculation_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cardImatriculation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string cardImatriculation = 7;</code>
     */
    public Builder setCardImatriculation(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cardImatriculation_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string cardImatriculation = 7;</code>
     */
    public Builder clearCardImatriculation() {
      
      cardImatriculation_ = getDefaultInstance().getCardImatriculation();
      onChanged();
      return this;
    }
    /**
     * <code>string cardImatriculation = 7;</code>
     */
    public Builder setCardImatriculationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cardImatriculation_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object cardNumber_ = "";
    /**
     * <code>string cardNumber = 8;</code>
     */
    public java.lang.String getCardNumber() {
      java.lang.Object ref = cardNumber_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cardNumber_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string cardNumber = 8;</code>
     */
    public com.google.protobuf.ByteString
        getCardNumberBytes() {
      java.lang.Object ref = cardNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cardNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string cardNumber = 8;</code>
     */
    public Builder setCardNumber(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cardNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string cardNumber = 8;</code>
     */
    public Builder clearCardNumber() {
      
      cardNumber_ = getDefaultInstance().getCardNumber();
      onChanged();
      return this;
    }
    /**
     * <code>string cardNumber = 8;</code>
     */
    public Builder setCardNumberBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cardNumber_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object cardUserSex_ = "";
    /**
     * <code>string cardUserSex = 9;</code>
     */
    public java.lang.String getCardUserSex() {
      java.lang.Object ref = cardUserSex_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cardUserSex_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string cardUserSex = 9;</code>
     */
    public com.google.protobuf.ByteString
        getCardUserSexBytes() {
      java.lang.Object ref = cardUserSex_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cardUserSex_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string cardUserSex = 9;</code>
     */
    public Builder setCardUserSex(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cardUserSex_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string cardUserSex = 9;</code>
     */
    public Builder clearCardUserSex() {
      
      cardUserSex_ = getDefaultInstance().getCardUserSex();
      onChanged();
      return this;
    }
    /**
     * <code>string cardUserSex = 9;</code>
     */
    public Builder setCardUserSexBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cardUserSex_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object cardUserPhoto_ = "";
    /**
     * <code>string cardUserPhoto = 10;</code>
     */
    public java.lang.String getCardUserPhoto() {
      java.lang.Object ref = cardUserPhoto_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cardUserPhoto_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string cardUserPhoto = 10;</code>
     */
    public com.google.protobuf.ByteString
        getCardUserPhotoBytes() {
      java.lang.Object ref = cardUserPhoto_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cardUserPhoto_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string cardUserPhoto = 10;</code>
     */
    public Builder setCardUserPhoto(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cardUserPhoto_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string cardUserPhoto = 10;</code>
     */
    public Builder clearCardUserPhoto() {
      
      cardUserPhoto_ = getDefaultInstance().getCardUserPhoto();
      onChanged();
      return this;
    }
    /**
     * <code>string cardUserPhoto = 10;</code>
     */
    public Builder setCardUserPhotoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cardUserPhoto_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object cardUserAdress_ = "";
    /**
     * <code>string cardUserAdress = 11;</code>
     */
    public java.lang.String getCardUserAdress() {
      java.lang.Object ref = cardUserAdress_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cardUserAdress_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string cardUserAdress = 11;</code>
     */
    public com.google.protobuf.ByteString
        getCardUserAdressBytes() {
      java.lang.Object ref = cardUserAdress_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cardUserAdress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string cardUserAdress = 11;</code>
     */
    public Builder setCardUserAdress(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cardUserAdress_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string cardUserAdress = 11;</code>
     */
    public Builder clearCardUserAdress() {
      
      cardUserAdress_ = getDefaultInstance().getCardUserAdress();
      onChanged();
      return this;
    }
    /**
     * <code>string cardUserAdress = 11;</code>
     */
    public Builder setCardUserAdressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cardUserAdress_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object cardUserPofession_ = "";
    /**
     * <code>string cardUserPofession = 12;</code>
     */
    public java.lang.String getCardUserPofession() {
      java.lang.Object ref = cardUserPofession_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cardUserPofession_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string cardUserPofession = 12;</code>
     */
    public com.google.protobuf.ByteString
        getCardUserPofessionBytes() {
      java.lang.Object ref = cardUserPofession_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cardUserPofession_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string cardUserPofession = 12;</code>
     */
    public Builder setCardUserPofession(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cardUserPofession_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string cardUserPofession = 12;</code>
     */
    public Builder clearCardUserPofession() {
      
      cardUserPofession_ = getDefaultInstance().getCardUserPofession();
      onChanged();
      return this;
    }
    /**
     * <code>string cardUserPofession = 12;</code>
     */
    public Builder setCardUserPofessionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cardUserPofession_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object cardUserFatherName_ = "";
    /**
     * <code>string cardUserFatherName = 13;</code>
     */
    public java.lang.String getCardUserFatherName() {
      java.lang.Object ref = cardUserFatherName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cardUserFatherName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string cardUserFatherName = 13;</code>
     */
    public com.google.protobuf.ByteString
        getCardUserFatherNameBytes() {
      java.lang.Object ref = cardUserFatherName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cardUserFatherName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string cardUserFatherName = 13;</code>
     */
    public Builder setCardUserFatherName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cardUserFatherName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string cardUserFatherName = 13;</code>
     */
    public Builder clearCardUserFatherName() {
      
      cardUserFatherName_ = getDefaultInstance().getCardUserFatherName();
      onChanged();
      return this;
    }
    /**
     * <code>string cardUserFatherName = 13;</code>
     */
    public Builder setCardUserFatherNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cardUserFatherName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object cardUserFatherBirthDate_ = "";
    /**
     * <code>string cardUserFatherBirthDate = 14;</code>
     */
    public java.lang.String getCardUserFatherBirthDate() {
      java.lang.Object ref = cardUserFatherBirthDate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cardUserFatherBirthDate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string cardUserFatherBirthDate = 14;</code>
     */
    public com.google.protobuf.ByteString
        getCardUserFatherBirthDateBytes() {
      java.lang.Object ref = cardUserFatherBirthDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cardUserFatherBirthDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string cardUserFatherBirthDate = 14;</code>
     */
    public Builder setCardUserFatherBirthDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cardUserFatherBirthDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string cardUserFatherBirthDate = 14;</code>
     */
    public Builder clearCardUserFatherBirthDate() {
      
      cardUserFatherBirthDate_ = getDefaultInstance().getCardUserFatherBirthDate();
      onChanged();
      return this;
    }
    /**
     * <code>string cardUserFatherBirthDate = 14;</code>
     */
    public Builder setCardUserFatherBirthDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cardUserFatherBirthDate_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object cardUserMatherBirthDate_ = "";
    /**
     * <code>string cardUserMatherBirthDate = 15;</code>
     */
    public java.lang.String getCardUserMatherBirthDate() {
      java.lang.Object ref = cardUserMatherBirthDate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cardUserMatherBirthDate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string cardUserMatherBirthDate = 15;</code>
     */
    public com.google.protobuf.ByteString
        getCardUserMatherBirthDateBytes() {
      java.lang.Object ref = cardUserMatherBirthDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cardUserMatherBirthDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string cardUserMatherBirthDate = 15;</code>
     */
    public Builder setCardUserMatherBirthDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cardUserMatherBirthDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string cardUserMatherBirthDate = 15;</code>
     */
    public Builder clearCardUserMatherBirthDate() {
      
      cardUserMatherBirthDate_ = getDefaultInstance().getCardUserMatherBirthDate();
      onChanged();
      return this;
    }
    /**
     * <code>string cardUserMatherBirthDate = 15;</code>
     */
    public Builder setCardUserMatherBirthDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cardUserMatherBirthDate_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object cardUserMatherName_ = "";
    /**
     * <code>string cardUserMatherName = 16;</code>
     */
    public java.lang.String getCardUserMatherName() {
      java.lang.Object ref = cardUserMatherName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cardUserMatherName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string cardUserMatherName = 16;</code>
     */
    public com.google.protobuf.ByteString
        getCardUserMatherNameBytes() {
      java.lang.Object ref = cardUserMatherName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cardUserMatherName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string cardUserMatherName = 16;</code>
     */
    public Builder setCardUserMatherName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cardUserMatherName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string cardUserMatherName = 16;</code>
     */
    public Builder clearCardUserMatherName() {
      
      cardUserMatherName_ = getDefaultInstance().getCardUserMatherName();
      onChanged();
      return this;
    }
    /**
     * <code>string cardUserMatherName = 16;</code>
     */
    public Builder setCardUserMatherNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cardUserMatherName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object cardUserBirthDate_ = "";
    /**
     * <code>string cardUserBirthDate = 17;</code>
     */
    public java.lang.String getCardUserBirthDate() {
      java.lang.Object ref = cardUserBirthDate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cardUserBirthDate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string cardUserBirthDate = 17;</code>
     */
    public com.google.protobuf.ByteString
        getCardUserBirthDateBytes() {
      java.lang.Object ref = cardUserBirthDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cardUserBirthDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string cardUserBirthDate = 17;</code>
     */
    public Builder setCardUserBirthDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cardUserBirthDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string cardUserBirthDate = 17;</code>
     */
    public Builder clearCardUserBirthDate() {
      
      cardUserBirthDate_ = getDefaultInstance().getCardUserBirthDate();
      onChanged();
      return this;
    }
    /**
     * <code>string cardUserBirthDate = 17;</code>
     */
    public Builder setCardUserBirthDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cardUserBirthDate_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object cardUserBrithPlace_ = "";
    /**
     * <code>string cardUserBrithPlace = 18;</code>
     */
    public java.lang.String getCardUserBrithPlace() {
      java.lang.Object ref = cardUserBrithPlace_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cardUserBrithPlace_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string cardUserBrithPlace = 18;</code>
     */
    public com.google.protobuf.ByteString
        getCardUserBrithPlaceBytes() {
      java.lang.Object ref = cardUserBrithPlace_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cardUserBrithPlace_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string cardUserBrithPlace = 18;</code>
     */
    public Builder setCardUserBrithPlace(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cardUserBrithPlace_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string cardUserBrithPlace = 18;</code>
     */
    public Builder clearCardUserBrithPlace() {
      
      cardUserBrithPlace_ = getDefaultInstance().getCardUserBrithPlace();
      onChanged();
      return this;
    }
    /**
     * <code>string cardUserBrithPlace = 18;</code>
     */
    public Builder setCardUserBrithPlaceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cardUserBrithPlace_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object cardNocaisse_ = "";
    /**
     * <code>string cardNocaisse = 19;</code>
     */
    public java.lang.String getCardNocaisse() {
      java.lang.Object ref = cardNocaisse_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cardNocaisse_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string cardNocaisse = 19;</code>
     */
    public com.google.protobuf.ByteString
        getCardNocaisseBytes() {
      java.lang.Object ref = cardNocaisse_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cardNocaisse_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string cardNocaisse = 19;</code>
     */
    public Builder setCardNocaisse(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cardNocaisse_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string cardNocaisse = 19;</code>
     */
    public Builder clearCardNocaisse() {
      
      cardNocaisse_ = getDefaultInstance().getCardNocaisse();
      onChanged();
      return this;
    }
    /**
     * <code>string cardNocaisse = 19;</code>
     */
    public Builder setCardNocaisseBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cardNocaisse_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:CardManager.Card)
  }

  // @@protoc_insertion_point(class_scope:CardManager.Card)
  private static final com.lsmichel.akka.grpc.java.rabbitmq.Card DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.lsmichel.akka.grpc.java.rabbitmq.Card();
  }

  public static com.lsmichel.akka.grpc.java.rabbitmq.Card getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Card>
      PARSER = new com.google.protobuf.AbstractParser<Card>() {
    public Card parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Card(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Card> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Card> getParserForType() {
    return PARSER;
  }

  public com.lsmichel.akka.grpc.java.rabbitmq.Card getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

