

// Generated by Akka gRPC. DO NOT EDIT.
package com.lsmichel.akka.grpc.java.rabbitmq;

import akka.NotUsed;
import akka.Done;
import akka.annotation.*;
import akka.grpc.internal.*;
import akka.grpc.GrpcClientSettings;
import akka.grpc.javadsl.AkkaGrpcClient;
import akka.grpc.javadsl.SingleResponseRequestBuilder;
import akka.grpc.javadsl.StreamResponseRequestBuilder;
import akka.stream.ActorMaterializer;
import akka.stream.Materializer;
import akka.stream.OverflowStrategy;
import akka.stream.javadsl.Flow;
import akka.stream.javadsl.Sink;
import akka.stream.javadsl.Source;
import akka.stream.Materializer;

import io.grpc.*;


import static com.lsmichel.akka.grpc.java.rabbitmq.CardeManager.Serializers.*;


import java.util.concurrent.CompletionStage;
import scala.concurrent.ExecutionContext;
import scala.compat.java8.FutureConverters;
import scala.concurrent.Future;
import scala.concurrent.Promise;

public abstract class  CardeManagerClientPowerApi {
  
    /**
     * Lower level "lifted" version of the method, giving access to request metadata etc.
     * prefer postCard(com.lsmichel.akka.grpc.java.rabbitmq.Card) if possible.
     */
    
      public SingleResponseRequestBuilder<com.lsmichel.akka.grpc.java.rabbitmq.Card, com.lsmichel.akka.grpc.java.rabbitmq.CardCreateActionPerformed> postCard()
    
    {
        throw new java.lang.UnsupportedOperationException();
    }
  
}