

// Generated by Akka gRPC. DO NOT EDIT.
package com.lsmichel.akka.grpc.java.rabbitmq;

import java.util.Iterator;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionStage;

import akka.japi.Function;
import akka.http.javadsl.model.*;
import akka.stream.Materializer;

import akka.grpc.Codec;
import akka.grpc.Codecs;
import akka.grpc.ProtobufSerializer;
import akka.grpc.javadsl.GoogleProtobufSerializer;
import akka.grpc.javadsl.GrpcMarshalling;
import akka.grpc.javadsl.GrpcExceptionHandler;

import static com.lsmichel.akka.grpc.java.rabbitmq.CardeManager.Serializers.*;

public class CardeManagerHandlerFactory {

  private static final CompletionStage<HttpResponse> notFound = CompletableFuture.completedFuture(
    HttpResponse.create().withStatus(StatusCodes.NOT_FOUND));

  /**
   * Creates a `HttpRequest` to `HttpResponse` handler that can be used in for example `Http().bindAndHandleAsync`
   * for the generated partial function handler and ends with `StatusCodes.NotFound` if the request is not matching.
   *
   * Use `akka.grpc.scaladsl.ServiceHandler.concatOrNotFound` with `CardeManagerHandler.partial` when combining
   * several services.
   */
  public static Function<HttpRequest, CompletionStage<HttpResponse>> create(CardeManager implementation, Materializer mat) {
    return create(implementation, CardeManager.name, mat);
  }

  /**
   * Creates a `HttpRequest` to `HttpResponse` handler that can be used in for example `Http().bindAndHandleAsync`
   * for the generated partial function handler and ends with `StatusCodes.NotFound` if the request is not matching.
   *
   * Use `akka.grpc.scaladsl.ServiceHandler.concatOrNotFound` with `CardeManagerHandler.partial` when combining
   * several services.
   *
   * Registering a gRPC service under a custom prefix is not widely supported and strongly discouraged by the specification.
   */
  public static Function<HttpRequest, CompletionStage<HttpResponse>> create(CardeManager implementation, String prefix, Materializer mat) {
    return partial(implementation, prefix, mat);
  }

  /**
   * Creates a `HttpRequest` to `HttpResponse` handler that can be used in for example
   * `Http.get(system).bindAndHandleAsync`. It ends with `StatusCodes.NotFound` if the request is not matching.
   *
   * Use `akka.grpc.javadsl.ServiceHandler.concatOrNotFound` when combining several services.
   */
  public static Function<HttpRequest, CompletionStage<HttpResponse>> partial(CardeManager implementation, String prefix, Materializer mat) {
    return (req -> {
      Iterator<String> segments = req.getUri().pathSegments().iterator();
      if (segments.hasNext() && segments.next().equals(prefix) && segments.hasNext()) {
        String method = segments.next();
        if (segments.hasNext()) return notFound; // we don't allow any random `/prefix/Method/anything/here
        else return handle(req, method, implementation, mat).exceptionally(e -> GrpcExceptionHandler.standard(e));
      } else {
        return notFound;
      }
    });
  }

  public String getServiceName() {
    return CardeManager.name;
  }

  private static CompletionStage<HttpResponse> handle(HttpRequest request, String method, CardeManager implementation, Materializer mat) {
    Codec responseCodec = Codecs.negotiate(request);
    switch(method) {
      
      case "PostCard":
        return GrpcMarshalling.unmarshal(request, CardSerializer, mat)
          .thenCompose(e -> implementation.postCard(e))
          .thenApply(e -> GrpcMarshalling.marshal(e, CardCreateActionPerformedSerializer, mat, responseCodec));
      
      default:
        CompletableFuture<HttpResponse> result = new CompletableFuture<>();
        result.completeExceptionally(new UnsupportedOperationException("Not implemented: " + method));
        return result;
    }
  }

}
