// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proj.proto

package com.lsmichel.akka.grpc.java.rabbitmq;

public interface CardCreateActionPerformedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CardManager.CardCreateActionPerformed)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string errorMessage = 1;</code>
   */
  java.lang.String getErrorMessage();
  /**
   * <code>string errorMessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();

  /**
   * <code>bool hasError = 2;</code>
   */
  boolean getHasError();

  /**
   * <code>string message = 3;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 3;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>string numcard = 4;</code>
   */
  java.lang.String getNumcard();
  /**
   * <code>string numcard = 4;</code>
   */
  com.google.protobuf.ByteString
      getNumcardBytes();
}
